### ISSUE TITLE
install-rtpproxy.sh: no such file or directory

### ISSUE THREAD

**Issue by wuxxin** [Ntipa/docker-kamailio#1]
hi, i found your kamailio docker config, and while trying it, it bailed out with "install-rtpproxy.sh" not found, and it is missing in the repo. maybe you havend included it in your commit and it is already existing ?

thanks if you look at it,
  wuxxin

**Comment by dgiglio** [comment]
Dear wuxxin

Sorry for your incovenience, I had actually forgot to include some files. I've fixed now, feel free to test it and please don't exitate to tell me if other issues raise.

Best regards
Daniele

**Comment by wuxxin** [comment]
Dear dgiglio,

 thank you for your answer, i will look into it today,
 _Update_: i looked into it, but found no push, but no hurry, i'll look at it when you push it

   best regards
    wuxxin

**Comment by dgiglio** [comment]
Dear wuxxin
Sorry for my delay, but I'm quite new with git and coming from subversion I still am not accustomed with its philosophy with commit+push, and sometimes I mess it up.
